
spring:
  application:
    name: doWith
  datasource: #mysql setting: local
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doWith
    username: root
    password: dbdPwl0816*
  jpa:
    hibernate:
      ddl-auto: update #이후 빼주기!!!!!!!

#jwt setting
jwt:
  secretKey: x!A%D*G-KaPdSgVkYp3sTD8y/B?E(H+M
  expiration_time: 3600000 #1시간(s)

server:
  port: 80